version: '3.7'

services:
  app:
    build: .
    container_name: app
    ports:
      - '3100:3100'
    depends_on:
      - db
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    stdin_open: true
    tty: true

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
